/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_etek_ircore_IRCore */

#ifndef _Included_com_etek_ircore_IRCore
#define _Included_com_etek_ircore_IRCore
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_etek_ircore_IRCore
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_etek_ircore_IRCore_init
  (JNIEnv *, jclass);

/*
 * Class:     com_etek_ircore_IRCore
 * Method:    close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_etek_ircore_IRCore_close
  (JNIEnv *, jclass);

/*
 * Class:     com_etek_ircore_IRCore
 * Method:    write
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_etek_ircore_IRCore_write
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_etek_ircore_IRCore
 * Method:    read
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_etek_ircore_IRCore_read
  (JNIEnv *, jclass, jint);




JNIEXPORT jint JNICALL Java_com_etek_ircore_IRCore_readVersion(JNIEnv* );


JNIEXPORT void JNICALL Java_com_etek_ircore_IRCore_setLearnTimeout(JNIEnv* , jobject ,
                                                 jint );

JNIEXPORT jint JNICALL Java_com_etek_ircore_IRCore_learnLoop(JNIEnv* );


JNIEXPORT jint JNICALL Java_com_etek_ircore_IRCore_recLearnStart(JNIEnv* );


JNIEXPORT jint  JNICALL Java_com_etek_ircore_IRCore_setCurrent(JNIEnv* ,jclass ,jint );


#ifdef __cplusplus
}
#endif
#endif
