/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_etek_ircore_LearnDecode */

#ifndef _Included_com_etek_ircore_LearnDecode
#define _Included_com_etek_ircore_LearnDecode
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_etek_ircore_LearnDecode
 * Method:    getET4007LearnCode
 * Signature: ([B)[B
 */

#define MAX_SIZE 1024
#define MAX_INDEX 64
#define MAX_SAMPLE 16
#define MAX_SAMPLE_INDEX 32
#define MAX_DATA 310
#define MAX_ORIGINAL_DATA 620
#define MAX_SEND_DATA 380

#define COMPARE_OFFSET 3
#define		_ET4007_CONTROL_SEND_CODE_3_		0x54
JNIEXPORT jbyteArray JNICALL Java_com_etek_ircore_LearnDecode_getET4007LearnCode(JNIEnv *, jclass, jbyteArray);
JNIEXPORT jbyteArray JNICALL Java_com_etek_ircore_LearnDecode_getET4003LearnCode(JNIEnv *, jclass, jbyteArray);
JNIEXPORT jbyteArray JNICALL Java_com_etek_ircore_LearnDecode_getET4207LearnCode(JNIEnv *, jclass, jbyteArray);
#ifdef __cplusplus
}
#endif
#endif
