
;==========================================
;RECEIVER LEARN SUBROUTINE
;OUTPUT 
;========================================== 

RECEIVER_START:
		SETDP	02h
		CLRF	state_flag
		CLRF	FLAG
		BCF		PT1EN,REC
REC_SET_REG:
		MOVLW	ADDRESS_PartIndexCount
	;	MOVWF	p_PartIndexCount
	;	MOVLW	ADDRESS_Sample
		MOVWF	FRS0
		MOVWF	p_Sample
		MOVLW	ADDRESS_Index
		
		MOVWF	p_Index
		CLRF	nIndexCount_h
		CLRF	nIndexCount_l
		
	    MOVLW	00000100b					;timera时钟源,内部时钟源mclk(111-5MHz)
		MOVWF	TCCONA
		CLRF	TSETAL
		CLRF	TSETAH
		CLRF	nIndexCount_l
		CLRF	nIndexCount_H
		BCF		INTE,TMAIE
		BCF		INTE,GIE
	   	BCF		PWMCON,TCOUTA_DIR			;TIMER UP 16bit型
		_GREEN_SET
		_RED_SET
		_ET4207_BUSY_
REC_WAIT_FIRST_DOWN_EDGE:
		BTFSC	PT1,REC
		GOTO	REC_WAIT_FIRST_DOWN_EDGE

		BCF		TCCONA,TCRSTA
		BSF		TCCONA,TCENA
		CLRF	TSETAL
		CLRF	TSETAH
		BSF		INTE,TMAIE
		BSF		INTE,GIE
REC_WAIT_UP_EDGE:
		BTFSS	PT1,REC
		GOTO	REC_WAIT_UP_EDGE
		CALL	PUSH_TIME_REG
	;	MOVFW	TCOUTAH
	;	MOVWF	nHighLevel_H
	;	MOVFW	TCOUTAL
	;	MOVWF	nHighLevel_L
		BCF		TCCONA,TCRSTA
	;	CLRF	TCOUTAH
	;	CLRF	TCOUTAL
REC_WAIT_DOWN_EDGE:
		BTFSC		FLAG,bLearnEnd	
		GOTO	REC_LEARN_END
		BTFSC	PT1,REC
		GOTO	REC_WAIT_DOWN_EDGE
		CALL	PUSH_TIME_REG
	;	MOVFW	TCOUTAH
;		MOVWF	nLowLevel_H

	;	MOVFW	TCOUTAL
	;	MOVWF	nLowLevel_L
		BCF		TCCONA,TCRSTA
	;	CLRF	TCOUTAH
	;	CLRF	TCOUTAL
		GOTO	REC_WAIT_UP_EDGE
PUSH_TIME_REG:
		MOVFW	TCOUTAH
		MOVWF	IND0
		INCF	FRS0,F
		MOVFW	TCOUTAL
		MOVWF	IND0
		INCFSZ	FRS0,F
		GOTO	$+2
		SETDP	01h
		INCFSZ	nIndexCount_l,F
		GOTO	$+2
		INCF	nIndexCount_H,F
		RETURN 

REC_LEARN_END:

		MOVLW	0FFH
		MOVWF	IND0
		INCF	FRS0,F
		MOVLW	0FFH
		MOVWF	IND0
		INCFSZ	FRS0,F
		GOTO	$+2
		SETDP	01h
		INCFSZ	nIndexCount_l,F
		GOTO	$+2
		INCF	nIndexCount_H,F
		_ET4207_NOT_BUSY_
		NOP
		MOVLW	40H
		MOVWF	LEARN_TYPE
		GOTO	SleepMode


