
;==========================================
;RECEIVER LEARN SUBROUTINE
;OUTPUT 
;========================================== 

RECEIVER_START:
		SETDP	02h
		CLRF	state_flag
		CLRF	FLAG
		BCF		PT1EN,REC
REC_SET_REG:
		MOVLW	ADDRESS_PartIndexCount
		MOVWF	p_PartIndexCount
		MOVLW	ADDRESS_Sample
		MOVWF	p_Sample
		MOVLW	ADDRESS_Index
		MOVWF	p_Index
		CLRF	nIndexCount_h
		CLRF	nIndexCount_l

	    MOVLW	00000110b					;timera时钟源,内部时钟源mclk(111-5MHz)
		MOVWF	TCCONA
		CLRF	TSETAL
		CLRF	TSETAH
		CLRF	nCount
REC_WAIT_FIRST_DOWN_EDGE:
		BTFSC	PT1,REC
		GOTO	REC_WAIT_FIRST_DOWN_EDGE

		BSF		TCCONA,TCRSTA
		BSF		TCCONA,TCENA
		CLRF	TSETAL
		CLRF	TSETAH
		BSF		INTE,TMAIE
		BSF		INTE,GIE
REC_WAIT_UP_EDGE:
		BTFSS	PT1,REC
		GOTO	REC_WAIT_UP_EDGE
	;	CALL	PUSH_TIME_REG
		MOVFW	TCOUTAH
		MOVWF	nHighLevel_H
		MOVFW	TCOUTAL
		MOVWF	nHighLevel_L
		BCF		TCCONA,TCRSTA
		_ET4207_BUSY_
REC_WAIT_DOWN_EDGE:
		BTFSC	FLAG,bLearnEnd
		GOTO	REC_LEARN_END
		BTFSC	PT1,REC
		GOTO	REC_WAIT_DOWN_EDGE
	;	CALL	PUSH_TIME_REG
		MOVFW	TCOUTAH
		MOVWF	nLowLevel_H

		MOVFW	TCOUTAL
		MOVWF	nLowLevel_L
		BCF		TCCONA,TCRSTA

		GOTO	REC_WAIT_UP_EDGE
REC_LEARN_END:
		nop
		_ET4207_NOT_BUSY_
		GOTO	SleepMode

PUSH_TIME_REG:
		MOVFW	TCOUTAH
		MOVWF	IND1
		INCF	FRS1,F
		MOVFW	TCOUTAL
		MOVWF	IND1
		INCF	FRS1,F
		INCF	nCount,F
		RETURN 

